import type { NextPage } from 'next';
import Head from 'next/head';
import Skills from '../components/Skills';
import WorkExperience from '../components/WorkExperience';
import About from '../components/About';
import Header from '../components/Header';
import Hero from '../components/Hero';




const Home: NextPage = () => {
  return (
    <div className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-scroll z-0'>
      <Head>
        <title>risvin portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      {/*Hero*/}  
      <section id="hero" className='snap-start'>
        <Hero/>
      </section>

      {/*About*/}
      <section id="about" className='snap-center'>
        <About />
      </section>

      {/*experience*/}
      <section id="experience" className='snap-center'>
        <WorkExperience />
      </section>

      {/* skills */}
      <section id="skills" className='snap-center'>
        <Skills />
      </section>








    </div>
  )
}

export default Home
